import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { MyStepByStepForm } from '../src/components/MyStepByStepForm';
import styles from '../styles/Home.module.css';
import { Box, Heading, Link } from '@chakra-ui/react';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Heading mb={'20'}>
          Welcome to
          <Link href='https://renft.io' isExternal>
            {' '}
            reNFT{' '}
          </Link>
          challenge
        </Heading>

        <Box margin={'20'} width={240}>
          <MyStepByStepForm />
        </Box>
      </main>
    </div>
  );
};

export default Home;
